import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, Loader2 } from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { DashboardLayout } from '@/components/layout/DashboardLayout'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

type Entry = { id: string; name: string; email: string; cohortYear: number | null; completion: number; affiliationStatus: string; accountStatus: string; lastLoginAt: string | null; field: { labelKey: string } | null; projects: Array<{ id: string; title: string; status: string }> }
export default function InstitutionDirectoryPage() {
  const [entries, setEntries] = useState<Entry[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { void Promise.resolve().then(async () => { const overview = await apiClient.get<{ organizations: Array<{ id: string }> }>('/institution/overview'); const id = overview.organizations[0]?.id; if (!id) return; const result = await apiClient.get<{ directory: Entry[] }>(`/institution/directory?organizationId=${id}`); setEntries(result.directory) }).catch(() => setError('Impossible de charger l’annuaire.')).finally(() => setLoading(false)) }, [])
  const filtered = entries.filter((entry) => `${entry.name} ${entry.email}`.toLowerCase().includes(search.toLowerCase()))
  return <DashboardLayout><main className="min-h-screen bg-muted/20 p-6 lg:p-10"><div className="mx-auto max-w-6xl space-y-6"><Link to="/institution" className="inline-flex items-center text-sm text-muted-foreground"><ArrowLeft className="mr-2 h-4 w-4" />Retour à la console</Link><header><p className="text-sm font-semibold uppercase tracking-wider text-primary">Console établissement</p><h1 className="mt-2 text-3xl font-bold">Annuaire des affiliés</h1><p className="mt-2 text-muted-foreground">Identité réelle des affiliés de votre établissement uniquement. Les conversations, projets privés et données de genre ne sont pas accessibles.</p></header><Card><CardHeader><CardTitle>Rechercher un affilié</CardTitle></CardHeader><CardContent><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Nom ou adresse email" className="h-10 w-full rounded-md border bg-background px-3" /></CardContent></Card>{error && <p className="text-sm text-destructive">{error}</p>}<Card><CardContent className="p-0">{loading ? <div className="flex justify-center p-10"><Loader2 className="h-5 w-5 animate-spin" /></div> : filtered.length === 0 ? <p className="p-10 text-center text-muted-foreground">Aucun affilié trouvé.</p> : <div className="divide-y">{filtered.map((entry) => <div key={entry.id} className="grid gap-3 p-4 md:grid-cols-[minmax(220px,1fr)_180px_120px_120px] md:items-center"><div><p className="font-semibold">{entry.name}</p><p className="text-sm text-muted-foreground">{entry.email}</p></div><span className="text-sm text-muted-foreground">{entry.field?.labelKey ?? 'Filière non renseignée'} · {entry.cohortYear ?? '—'}</span><span className="text-sm">Profil : {entry.completion}%</span><span className="rounded-full bg-muted px-3 py-1 text-center text-xs font-semibold">{entry.affiliationStatus}</span></div>)}</div>}</CardContent></Card></div></main></DashboardLayout>
}
