import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, Loader2 } from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { DashboardLayout } from '@/components/layout/DashboardLayout'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

type Affiliation = { id: string; email: string; status: string; accountStatus: string; cohortYear: number | null; field: { labelKey: string } | null }
export default function InstitutionAffiliationsPage() {
  const [items, setItems] = useState<Affiliation[]>([]); const [selected, setSelected] = useState<string[]>([]); const [status, setStatus] = useState('LEAVING'); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState(''); const load = async () => { const overview = await apiClient.get<{ organizations: Array<{ id: string }> }>('/institution/overview'); const id = overview.organizations[0]?.id; if (!id) return; const data = await apiClient.get<{ affiliations: Affiliation[] }>(`/institution/affiliations?organizationId=${id}`); setItems(data.affiliations) }; useEffect(() => { void Promise.resolve().then(load).catch(() => setMessage('Impossible de charger les affiliations.')) }, [])
  const bulk = async () => { try { await apiClient.post('/institution/affiliations/bulk-status', { affiliationIds: selected, status, confirmation }); setMessage(`${selected.length} affiliation(s) mise(s) à jour.`); setSelected([]); setConfirmation(''); await load() } catch { setMessage(`Saisissez MODIFIER ${selected.length} pour confirmer.`) } }
  return <DashboardLayout><main className="min-h-screen bg-muted/20 p-6 lg:p-10"><div className="mx-auto max-w-6xl space-y-6"><Link to="/institution" className="inline-flex items-center text-sm text-muted-foreground"><ArrowLeft className="mr-2 h-4 w-4" />Retour à la console</Link><header><p className="text-sm font-semibold uppercase tracking-wider text-primary">Console établissement</p><h1 className="mt-2 text-3xl font-bold">Affiliations et statuts</h1><p className="mt-2 text-muted-foreground">Les changements sont audités. Les données de genre ne sont jamais affichées.</p></header>{message && <p className="text-sm text-destructive">{message}</p>}{selected.length > 0 && <Card><CardHeader><CardTitle>Modifier {selected.length} affiliation(s)</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3"><select className="h-10 rounded-md border bg-background px-3" value={status} onChange={(e) => setStatus(e.target.value)}><option value="ACTIVE">Active</option><option value="LEAVING">Sortant</option><option value="ALUMNI">Alumni</option><option value="SUSPENDED">Suspendue</option></select><input className="h-10 rounded-md border px-3" placeholder={`MODIFIER ${selected.length}`} value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /><Button onClick={bulk}>Confirmer</Button></CardContent></Card>}<Card><CardHeader><CardTitle>Affiliés</CardTitle></CardHeader><CardContent>{items.length === 0 ? <div className="py-8 text-center text-muted-foreground"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></div> : <div className="divide-y">{items.map((item) => <label key={item.id} className="flex items-center gap-4 py-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, item.id] : selected.filter((id) => id !== item.id))} /><span className="flex-1"><span className="block font-medium">{item.email}</span><span className="text-sm text-muted-foreground">{item.field?.labelKey ?? 'Filière non renseignée'} · {item.cohortYear ?? 'Promotion non renseignée'} · {item.accountStatus}</span></span><span className="rounded-full bg-muted px-3 py-1 text-xs font-semibold">{item.status}</span></label>)}</div>}</CardContent></Card></div></main></DashboardLayout>
}
