import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Activity, ArrowLeft, Loader2, ShieldCheck } from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { DashboardLayout } from '@/components/layout/DashboardLayout'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

type Health = { generatedAt: string; threshold: number; activation: { invited: number | null; activated: number | null; rate: number | null }; profileCompletionAverage: number | null; projectsByStatus: Record<string, number>; acceptedMatchRate: number | null; applicationResponseMedianHours: number | null; moderation: { volume: number | null; medianResolutionHours: number | null }; invitationBounceRate: number | null }
const format = (value: number | null, suffix = '') => value === null ? 'Effectif insuffisant pour publier ce chiffre' : `${value}${suffix}`
export default function ProductHealthPage() { const [health, setHealth] = useState<Health | null>(null); const [error, setError] = useState(''); useEffect(() => { void Promise.resolve().then(() => apiClient.get<Health>('/staff/health')).then(setHealth).catch(() => setError('Accès réservé à OPS_ADMIN ou SUPER_ADMIN.')) }, [])
  return <DashboardLayout><main className="min-h-screen bg-muted/20 p-6 lg:p-10"><div className="mx-auto max-w-7xl space-y-6"><Link to="/feed" className="inline-flex items-center text-sm text-muted-foreground"><ArrowLeft className="mr-2 h-4 w-4" />Retour</Link><header><p className="text-sm font-semibold uppercase tracking-wider text-primary">Console staff</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-bold"><Activity className="h-7 w-7" />Santé produit</h1><p className="mt-2 text-muted-foreground">Agrégats plateforme uniquement. Les séries temporelles et cohortes sont réservées à une version ultérieure.</p></header>{error && <p role="status" className="text-sm text-muted-foreground">{error}</p>}{!health && !error ? <Loader2 className="h-5 w-5 animate-spin" /> : health && <><div className="grid gap-4 md:grid-cols-3"><Metric title="Taux d’activation" value={format(health.activation.rate, '%')} detail={`${format(health.activation.activated)} activés sur ${format(health.activation.invited)} invités`} /><Metric title="Complétion moyenne" value={format(health.profileCompletionAverage, '%')} /><Metric title="Mise en relation acceptée" value={format(health.acceptedMatchRate, '%')} /></div><div className="grid gap-4 md:grid-cols-2"><Metric title="Réponse médiane aux candidatures" value={format(health.applicationResponseMedianHours, ' h')} /><Metric title="Rebond des invitations" value={format(health.invitationBounceRate, '%')} /><Metric title="Modération" value={format(health.moderation.volume)} detail={`Délai médian : ${format(health.moderation.medianResolutionHours, ' h')}`} /><Card><CardHeader><CardTitle>Projets par état</CardTitle></CardHeader><CardContent><dl className="grid grid-cols-2 gap-3 text-sm">{Object.entries(health.projectsByStatus).map(([status, count]) => <div key={status} className="rounded-md bg-muted/50 p-3"><dt className="text-muted-foreground">{status}</dt><dd className="text-xl font-semibold">{count}</dd></div>)}</dl></CardContent></Card></div><p className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4" />Seuil de confidentialité appliqué : {health.threshold} observations.</p></>}</div></main></DashboardLayout> }
function Metric({ title, value, detail }: { title: string; value: string; detail?: string }) { return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{value}</p>{detail && <p className="mt-2 text-sm text-muted-foreground">{detail}</p>}</CardContent></Card> }
