import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, Plus, ShieldCheck } from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { DashboardLayout } from '@/components/layout/DashboardLayout'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

type Kind = 'skills' | 'fields' | 'sectors' | 'regions'
type Item = { id: string; slug: string; labelKey: string; category: string | null; countryCode: string | null; isActive: boolean; sortOrder: number; usageCount: number }
const kinds: Array<{ key: Kind; label: string }> = [{ key: 'skills', label: 'Compétences' }, { key: 'fields', label: 'Filières' }, { key: 'sectors', label: 'Secteurs' }, { key: 'regions', label: 'Régions' }]

export default function ReferenceDataPage() {
  const [kind, setKind] = useState<Kind>('skills'); const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [draft, setDraft] = useState({ slug: '', labelKey: '', category: '', countryCode: 'MG', sortOrder: '0' })
  const load = useCallback(async () => { setLoading(true); try { const data = await apiClient.get<{ items: Item[] }>(`/staff/reference-data/${kind}`); setItems(data.items); setMessage('') } catch { setMessage('Accès réservé à SUPER_ADMIN ou chargement impossible.') } finally { setLoading(false) } }, [kind])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  const create = async () => { try { await apiClient.post(`/staff/reference-data/${kind}`, { slug: draft.slug, labelKey: draft.labelKey, category: draft.category || null, countryCode: kind === 'regions' ? draft.countryCode : undefined, sortOrder: Number(draft.sortOrder), isActive: true }); setDraft({ slug: '', labelKey: '', category: '', countryCode: 'MG', sortOrder: '0' }); await load(); setMessage('Entrée créée. La clé i18n est maintenant disponible pour les traductions.') } catch { setMessage('Création impossible : vérifiez le slug et la clé i18n.') } }
  const toggle = async (item: Item) => { try { await apiClient.patch(`/staff/reference-data/${kind}/${item.id}`, { isActive: !item.isActive }); await load() } catch { setMessage('Modification impossible.') } }
  return <DashboardLayout><main className="min-h-screen bg-muted/20 p-6 lg:p-10"><div className="mx-auto max-w-7xl space-y-6"><Link to="/feed" className="inline-flex items-center text-sm text-muted-foreground"><ArrowLeft className="mr-2 h-4 w-4" />Retour</Link><header><p className="text-sm font-semibold uppercase tracking-wider text-primary">Console staff</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-bold"><ShieldCheck className="h-7 w-7" />Référentiels</h1><p className="mt-2 text-muted-foreground">Les entrées sont désactivées, jamais supprimées. Les sélecteurs publics ne proposent que les entrées actives.</p></header><div className="flex flex-wrap gap-2">{kinds.map((entry) => <Button key={entry.key} variant={kind === entry.key ? 'default' : 'outline'} onClick={() => setKind(entry.key)}>{entry.label}</Button>)}</div><Card><CardHeader><CardTitle>Ajouter une entrée</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-5"><input className="h-10 rounded-md border bg-background px-3" placeholder="slug-exemple" value={draft.slug} onChange={(e) => setDraft({ ...draft, slug: e.target.value })} /><input className="h-10 rounded-md border bg-background px-3" placeholder="i18n.reference.exemple" value={draft.labelKey} onChange={(e) => setDraft({ ...draft, labelKey: e.target.value })} /><input className="h-10 rounded-md border bg-background px-3" placeholder="Catégorie (optionnel)" value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })} /><input className="h-10 rounded-md border bg-background px-3" placeholder="Ordre" type="number" value={draft.sortOrder} onChange={(e) => setDraft({ ...draft, sortOrder: e.target.value })} /><Button onClick={() => void create()}><Plus className="mr-2 h-4 w-4" />Ajouter</Button></div></CardContent></Card>{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}<Card><CardHeader><CardTitle>{kinds.find((entry) => entry.key === kind)?.label}</CardTitle></CardHeader><CardContent>{loading ? <p>Chargement…</p> : items.length === 0 ? <p className="py-8 text-muted-foreground">Aucune entrée.</p> : <div className="divide-y">{items.map((item) => <div key={item.id} className="grid gap-2 py-4 text-sm md:grid-cols-[1fr_1fr_1fr_100px_130px]"><span className="font-semibold">{item.labelKey}</span><span className="text-muted-foreground">{item.slug}</span><span>{item.category ?? item.countryCode ?? '—'}</span><span>{item.usageCount} usage{item.usageCount > 1 ? 's' : ''}</span><Button size="sm" variant="outline" onClick={() => void toggle(item)}>{item.isActive ? 'Désactiver' : 'Réactiver'}</Button></div>)}</div>}</CardContent></Card></div></main></DashboardLayout>
}
